/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PageLayout: typeof import('./src/components/page-layout/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
